version: '3.8'

services:
  servidor:
    build: .
    container_name: socket_servidor
    command: ./servidor
    ports:
      - "65432:65432"

  cliente:
    build: .
    command: ./cliente
    depends_on:
      - servidor